// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthResponse struct {
	Token                string               `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expires              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

type AuthRequest struct {
	// Types that are valid to be assigned to Key:
	//	*AuthRequest_ApiKey
	Key                  isAuthRequest_Key `protobuf_oneof:"key"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

type isAuthRequest_Key interface {
	isAuthRequest_Key()
}

type AuthRequest_ApiKey struct {
	ApiKey *ApiKey `protobuf:"bytes,1,opt,name=apiKey,proto3,oneof"`
}

func (*AuthRequest_ApiKey) isAuthRequest_Key() {}

func (m *AuthRequest) GetKey() isAuthRequest_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AuthRequest) GetApiKey() *ApiKey {
	if x, ok := m.GetKey().(*AuthRequest_ApiKey); ok {
		return x.ApiKey
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AuthRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AuthRequest_ApiKey)(nil),
	}
}

type ApiKey struct {
	KeyID                int64    `protobuf:"varint,1,opt,name=keyID,proto3" json:"keyID,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiKey) Reset()         { *m = ApiKey{} }
func (m *ApiKey) String() string { return proto.CompactTextString(m) }
func (*ApiKey) ProtoMessage()    {}
func (*ApiKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *ApiKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiKey.Unmarshal(m, b)
}
func (m *ApiKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiKey.Marshal(b, m, deterministic)
}
func (m *ApiKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiKey.Merge(m, src)
}
func (m *ApiKey) XXX_Size() int {
	return xxx_messageInfo_ApiKey.Size(m)
}
func (m *ApiKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiKey.DiscardUnknown(m)
}

var xxx_messageInfo_ApiKey proto.InternalMessageInfo

func (m *ApiKey) GetKeyID() int64 {
	if m != nil {
		return m.KeyID
	}
	return 0
}

func (m *ApiKey) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthResponse)(nil), "sendlix.api.v1.AuthResponse")
	proto.RegisterType((*AuthRequest)(nil), "sendlix.api.v1.AuthRequest")
	proto.RegisterType((*ApiKey)(nil), "sendlix.api.v1.ApiKey")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xdb, 0x6f, 0xbf, 0x8d, 0x74, 0x22, 0x1e, 0x16, 0x29, 0xa5, 0x0a, 0x96, 0x9c, 0x8a,
	0x87, 0x8d, 0x56, 0xf1, 0xde, 0x22, 0xfe, 0xa8, 0xb7, 0xa5, 0xa7, 0x5e, 0x24, 0x6d, 0xc7, 0x64,
	0xc9, 0x8f, 0x5d, 0xb3, 0x13, 0x6d, 0xfe, 0x7b, 0xe9, 0x6e, 0x82, 0x88, 0x9e, 0x96, 0xc7, 0x7b,
	0xfb, 0x99, 0x37, 0x03, 0x10, 0x55, 0x94, 0x70, 0x5d, 0x2a, 0x52, 0xec, 0xc4, 0x60, 0xb1, 0xcb,
	0xe4, 0x9e, 0x47, 0x5a, 0xf2, 0x8f, 0xeb, 0xf1, 0x45, 0xac, 0x54, 0x9c, 0x61, 0x68, 0xdd, 0x4d,
	0xf5, 0x16, 0x92, 0xcc, 0xd1, 0x50, 0x94, 0x6b, 0xf7, 0x21, 0x58, 0xc3, 0xf1, 0xbc, 0xa2, 0x44,
	0xa0, 0xd1, 0xaa, 0x30, 0xc8, 0x4e, 0xa1, 0x4f, 0x2a, 0xc5, 0x62, 0xd4, 0x9d, 0x74, 0xa7, 0x03,
	0xe1, 0x04, 0xbb, 0x85, 0x23, 0xdc, 0x6b, 0x59, 0xa2, 0x19, 0xfd, 0x9b, 0x74, 0xa7, 0xfe, 0x6c,
	0xcc, 0x1d, 0x98, 0xb7, 0x60, 0xbe, 0x6a, 0xc1, 0xa2, 0x8d, 0x06, 0x0f, 0xe0, 0x3b, 0xf6, 0x7b,
	0x85, 0x86, 0xd8, 0x15, 0x78, 0x91, 0x96, 0x2f, 0x58, 0x5b, 0xb6, 0x3f, 0x1b, 0xf2, 0x9f, 0x65,
	0xf9, 0xdc, 0xba, 0x4f, 0x1d, 0xd1, 0xe4, 0x16, 0x7d, 0xe8, 0xa5, 0x58, 0x07, 0x77, 0xe0, 0x39,
	0xeb, 0xd0, 0x2e, 0xc5, 0xfa, 0xf9, 0xde, 0x12, 0x7a, 0xc2, 0x09, 0x36, 0x04, 0xcf, 0xe0, 0xb6,
	0x44, 0xb2, 0xe5, 0x06, 0xa2, 0x51, 0x33, 0x01, 0xff, 0x0f, 0xf3, 0xd9, 0x12, 0xfc, 0x47, 0xa4,
	0xe5, 0x27, 0xad, 0xec, 0x32, 0x67, 0xbf, 0xe6, 0x7e, 0x97, 0x1c, 0x9f, 0xff, 0x6d, 0xba, 0xeb,
	0x04, 0x9d, 0xc5, 0xe5, 0x7a, 0x1a, 0x4b, 0x4a, 0xaa, 0x0d, 0xdf, 0xaa, 0x3c, 0x6c, 0xb2, 0x61,
	0xac, 0x5e, 0xcd, 0x2e, 0x0d, 0x65, 0x41, 0x58, 0x16, 0x51, 0xd6, 0x9c, 0xdb, 0xb3, 0xcf, 0xcd,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x6a, 0x7f, 0x6f, 0xa1, 0x01, 0x00, 0x00,
}
