// Code generated by protoc-gen-go. DO NOT EDIT.
// source: EmailData.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Email address information
type EmailData struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailData) Reset()         { *m = EmailData{} }
func (m *EmailData) String() string { return proto.CompactTextString(m) }
func (*EmailData) ProtoMessage()    {}
func (*EmailData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9301cf2e914caaf6, []int{0}
}

func (m *EmailData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailData.Unmarshal(m, b)
}
func (m *EmailData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailData.Marshal(b, m, deterministic)
}
func (m *EmailData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailData.Merge(m, src)
}
func (m *EmailData) XXX_Size() int {
	return xxx_messageInfo_EmailData.Size(m)
}
func (m *EmailData) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailData.DiscardUnknown(m)
}

var xxx_messageInfo_EmailData proto.InternalMessageInfo

func (m *EmailData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*EmailData)(nil), "EmailData")
}

func init() { proto.RegisterFile("EmailData.proto", fileDescriptor_9301cf2e914caaf6) }

var fileDescriptor_9301cf2e914caaf6 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x77, 0xcd, 0x4d, 0xcc,
	0xcc, 0x71, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe5, 0xe2, 0x84,
	0x0b, 0x09, 0x89, 0x70, 0xb1, 0xa6, 0x82, 0x38, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10,
	0x8e, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x10, 0xcc, 0x76, 0xd2,
	0x8a, 0xd2, 0x48, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0x4e, 0xcd,
	0x4b, 0xc9, 0xc9, 0xac, 0xd0, 0x4f, 0xcf, 0x8f, 0x2f, 0x4e, 0xc9, 0xd6, 0xcf, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x07, 0x5b, 0x91, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xa1, 0x39, 0x92, 0xb0, 0x7c, 0x00, 0x00, 0x00,
}
