// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmlMailRequest struct {
	Mail                 []byte           `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	AdditionalInfos      *AdditionalInfos `protobuf:"bytes,2,opt,name=additionalInfos,proto3" json:"additionalInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EmlMailRequest) Reset()         { *m = EmlMailRequest{} }
func (m *EmlMailRequest) String() string { return proto.CompactTextString(m) }
func (*EmlMailRequest) ProtoMessage()    {}
func (*EmlMailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{0}
}

func (m *EmlMailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmlMailRequest.Unmarshal(m, b)
}
func (m *EmlMailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmlMailRequest.Marshal(b, m, deterministic)
}
func (m *EmlMailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmlMailRequest.Merge(m, src)
}
func (m *EmlMailRequest) XXX_Size() int {
	return xxx_messageInfo_EmlMailRequest.Size(m)
}
func (m *EmlMailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmlMailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmlMailRequest proto.InternalMessageInfo

func (m *EmlMailRequest) GetMail() []byte {
	if m != nil {
		return m.Mail
	}
	return nil
}

func (m *EmlMailRequest) GetAdditionalInfos() *AdditionalInfos {
	if m != nil {
		return m.AdditionalInfos
	}
	return nil
}

type GroupMailData struct {
	GroupId  string     `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Subject  string     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	From     *EmailData `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Category string     `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*GroupMailData_TextContent
	Body                 isGroupMailData_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GroupMailData) Reset()         { *m = GroupMailData{} }
func (m *GroupMailData) String() string { return proto.CompactTextString(m) }
func (*GroupMailData) ProtoMessage()    {}
func (*GroupMailData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{1}
}

func (m *GroupMailData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMailData.Unmarshal(m, b)
}
func (m *GroupMailData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMailData.Marshal(b, m, deterministic)
}
func (m *GroupMailData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMailData.Merge(m, src)
}
func (m *GroupMailData) XXX_Size() int {
	return xxx_messageInfo_GroupMailData.Size(m)
}
func (m *GroupMailData) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMailData.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMailData proto.InternalMessageInfo

func (m *GroupMailData) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupMailData) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *GroupMailData) GetFrom() *EmailData {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GroupMailData) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type isGroupMailData_Body interface {
	isGroupMailData_Body()
}

type GroupMailData_TextContent struct {
	TextContent *MailContent `protobuf:"bytes,5,opt,name=TextContent,proto3,oneof"`
}

func (*GroupMailData_TextContent) isGroupMailData_Body() {}

func (m *GroupMailData) GetBody() isGroupMailData_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *GroupMailData) GetTextContent() *MailContent {
	if x, ok := m.GetBody().(*GroupMailData_TextContent); ok {
		return x.TextContent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GroupMailData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GroupMailData_TextContent)(nil),
	}
}

type SendEmailResponse struct {
	Message              []string `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	EmailsLeft           int64    `protobuf:"varint,2,opt,name=emailsLeft,proto3" json:"emailsLeft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{2}
}

func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailResponse.Unmarshal(m, b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(m, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendEmailResponse.Size(m)
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func (m *SendEmailResponse) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SendEmailResponse) GetEmailsLeft() int64 {
	if m != nil {
		return m.EmailsLeft
	}
	return 0
}

type MailContent struct {
	Html                 string   `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Tracking             bool     `protobuf:"varint,3,opt,name=tracking,proto3" json:"tracking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailContent) Reset()         { *m = MailContent{} }
func (m *MailContent) String() string { return proto.CompactTextString(m) }
func (*MailContent) ProtoMessage()    {}
func (*MailContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{3}
}

func (m *MailContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailContent.Unmarshal(m, b)
}
func (m *MailContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailContent.Marshal(b, m, deterministic)
}
func (m *MailContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailContent.Merge(m, src)
}
func (m *MailContent) XXX_Size() int {
	return xxx_messageInfo_MailContent.Size(m)
}
func (m *MailContent) XXX_DiscardUnknown() {
	xxx_messageInfo_MailContent.DiscardUnknown(m)
}

var xxx_messageInfo_MailContent proto.InternalMessageInfo

func (m *MailContent) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

func (m *MailContent) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MailContent) GetTracking() bool {
	if m != nil {
		return m.Tracking
	}
	return false
}

type AttachmentData struct {
	ContentUrl           string   `protobuf:"bytes,1,opt,name=contentUrl,proto3" json:"contentUrl,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Filename             string   `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachmentData) Reset()         { *m = AttachmentData{} }
func (m *AttachmentData) String() string { return proto.CompactTextString(m) }
func (*AttachmentData) ProtoMessage()    {}
func (*AttachmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{4}
}

func (m *AttachmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachmentData.Unmarshal(m, b)
}
func (m *AttachmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachmentData.Marshal(b, m, deterministic)
}
func (m *AttachmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachmentData.Merge(m, src)
}
func (m *AttachmentData) XXX_Size() int {
	return xxx_messageInfo_AttachmentData.Size(m)
}
func (m *AttachmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachmentData.DiscardUnknown(m)
}

var xxx_messageInfo_AttachmentData proto.InternalMessageInfo

func (m *AttachmentData) GetContentUrl() string {
	if m != nil {
		return m.ContentUrl
	}
	return ""
}

func (m *AttachmentData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AttachmentData) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type SendMailRequest struct {
	// Email recipient fields
	To  []*EmailData `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Cc  []*EmailData `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc []*EmailData `protobuf:"bytes,3,rep,name=bcc,proto3" json:"bcc,omitempty"`
	// Sender information
	From    *EmailData `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	ReplyTo *EmailData `protobuf:"bytes,5,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// Email content fields
	Subject         string           `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	AdditionalInfos *AdditionalInfos `protobuf:"bytes,7,opt,name=additionalInfos,proto3" json:"additionalInfos,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*SendMailRequest_TextContent
	Body                 isSendMailRequest_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SendMailRequest) Reset()         { *m = SendMailRequest{} }
func (m *SendMailRequest) String() string { return proto.CompactTextString(m) }
func (*SendMailRequest) ProtoMessage()    {}
func (*SendMailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{5}
}

func (m *SendMailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMailRequest.Unmarshal(m, b)
}
func (m *SendMailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMailRequest.Marshal(b, m, deterministic)
}
func (m *SendMailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMailRequest.Merge(m, src)
}
func (m *SendMailRequest) XXX_Size() int {
	return xxx_messageInfo_SendMailRequest.Size(m)
}
func (m *SendMailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMailRequest proto.InternalMessageInfo

func (m *SendMailRequest) GetTo() []*EmailData {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *SendMailRequest) GetCc() []*EmailData {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *SendMailRequest) GetBcc() []*EmailData {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func (m *SendMailRequest) GetFrom() *EmailData {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *SendMailRequest) GetReplyTo() *EmailData {
	if m != nil {
		return m.ReplyTo
	}
	return nil
}

func (m *SendMailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendMailRequest) GetAdditionalInfos() *AdditionalInfos {
	if m != nil {
		return m.AdditionalInfos
	}
	return nil
}

type isSendMailRequest_Body interface {
	isSendMailRequest_Body()
}

type SendMailRequest_TextContent struct {
	TextContent *MailContent `protobuf:"bytes,8,opt,name=TextContent,proto3,oneof"`
}

func (*SendMailRequest_TextContent) isSendMailRequest_Body() {}

func (m *SendMailRequest) GetBody() isSendMailRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *SendMailRequest) GetTextContent() *MailContent {
	if x, ok := m.GetBody().(*SendMailRequest_TextContent); ok {
		return x.TextContent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SendMailRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SendMailRequest_TextContent)(nil),
	}
}

type AdditionalInfos struct {
	Attachments          []*AttachmentData    `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Category             string               `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	SendAt               *timestamp.Timestamp `protobuf:"bytes,4,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AdditionalInfos) Reset()         { *m = AdditionalInfos{} }
func (m *AdditionalInfos) String() string { return proto.CompactTextString(m) }
func (*AdditionalInfos) ProtoMessage()    {}
func (*AdditionalInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{6}
}

func (m *AdditionalInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdditionalInfos.Unmarshal(m, b)
}
func (m *AdditionalInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdditionalInfos.Marshal(b, m, deterministic)
}
func (m *AdditionalInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdditionalInfos.Merge(m, src)
}
func (m *AdditionalInfos) XXX_Size() int {
	return xxx_messageInfo_AdditionalInfos.Size(m)
}
func (m *AdditionalInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_AdditionalInfos.DiscardUnknown(m)
}

var xxx_messageInfo_AdditionalInfos proto.InternalMessageInfo

func (m *AdditionalInfos) GetAttachments() []*AttachmentData {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *AdditionalInfos) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AdditionalInfos) GetSendAt() *timestamp.Timestamp {
	if m != nil {
		return m.SendAt
	}
	return nil
}

func init() {
	proto.RegisterType((*EmlMailRequest)(nil), "sendlix.api.v1.EmlMailRequest")
	proto.RegisterType((*GroupMailData)(nil), "sendlix.api.v1.GroupMailData")
	proto.RegisterType((*SendEmailResponse)(nil), "sendlix.api.v1.SendEmailResponse")
	proto.RegisterType((*MailContent)(nil), "sendlix.api.v1.MailContent")
	proto.RegisterType((*AttachmentData)(nil), "sendlix.api.v1.AttachmentData")
	proto.RegisterType((*SendMailRequest)(nil), "sendlix.api.v1.SendMailRequest")
	proto.RegisterType((*AdditionalInfos)(nil), "sendlix.api.v1.AdditionalInfos")
}

func init() { proto.RegisterFile("email.proto", fileDescriptor_6175298cb4ed6faa) }

var fileDescriptor_6175298cb4ed6faa = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6e, 0xd3, 0x40,
	0x10, 0x6e, 0x9c, 0x34, 0x3f, 0x93, 0x92, 0x88, 0x7d, 0xb2, 0x02, 0xa4, 0xc5, 0x12, 0x52, 0xc5,
	0x83, 0x23, 0xda, 0x03, 0x40, 0x0b, 0x15, 0x54, 0xa2, 0x0f, 0xdd, 0x86, 0x17, 0x5e, 0xca, 0xc6,
	0x9e, 0xb8, 0xa6, 0xb6, 0xd7, 0x78, 0x27, 0xa8, 0x39, 0x00, 0x37, 0xe1, 0x30, 0x1c, 0x82, 0xc3,
	0xa0, 0x5d, 0x3b, 0x96, 0xed, 0x14, 0xa9, 0xea, 0x93, 0x3d, 0xbf, 0xdf, 0xcc, 0x37, 0xb3, 0x03,
	0x43, 0x8c, 0x45, 0x18, 0xb9, 0x69, 0x26, 0x49, 0xb2, 0x91, 0xc2, 0xc4, 0x8f, 0xc2, 0x3b, 0x57,
	0xa4, 0xa1, 0xfb, 0xf3, 0xcd, 0x64, 0x3f, 0x90, 0x32, 0x88, 0x70, 0x66, 0xac, 0x8b, 0xd5, 0x72,
	0x46, 0x61, 0x8c, 0x8a, 0x44, 0x9c, 0xe6, 0x01, 0x93, 0xf1, 0x99, 0x8e, 0xfe, 0x20, 0x48, 0xe4,
	0x0a, 0x47, 0xc2, 0xe8, 0x2c, 0x8e, 0x2e, 0x44, 0x18, 0x71, 0xfc, 0xb1, 0x42, 0x45, 0x8c, 0x41,
	0x47, 0xfb, 0xd8, 0xad, 0x83, 0xd6, 0xe1, 0x1e, 0x37, 0xff, 0xec, 0x1c, 0xc6, 0xc2, 0xf7, 0x43,
	0x0a, 0x65, 0x22, 0xa2, 0xf3, 0x64, 0x29, 0x95, 0x6d, 0x1d, 0xb4, 0x0e, 0x87, 0x47, 0xfb, 0x6e,
	0xbd, 0x02, 0xf7, 0xa4, 0xee, 0xc6, 0x9b, 0x71, 0xce, 0x9f, 0x16, 0x3c, 0xf9, 0x98, 0xc9, 0x55,
	0x7a, 0x51, 0x14, 0xc2, 0x6c, 0xe8, 0x05, 0x5a, 0x71, 0xee, 0x1b, 0xcc, 0x01, 0xdf, 0x88, 0xda,
	0xa2, 0x56, 0x8b, 0xef, 0xe8, 0x91, 0x81, 0x1b, 0xf0, 0x8d, 0xc8, 0xa6, 0xd0, 0x59, 0x66, 0x32,
	0xb6, 0xdb, 0xa6, 0x0a, 0x70, 0xcb, 0xb6, 0xb8, 0xd1, 0xb3, 0x09, 0xf4, 0x3d, 0x41, 0x18, 0xc8,
	0x6c, 0x6d, 0x77, 0x4c, 0x68, 0x29, 0xb3, 0xb7, 0x30, 0x9c, 0xe3, 0x1d, 0xbd, 0x97, 0x09, 0x61,
	0x42, 0xf6, 0xae, 0x49, 0xf1, 0xac, 0xd9, 0x88, 0x2e, 0xaf, 0x70, 0xf9, 0xb4, 0xc3, 0xab, 0x11,
	0xa7, 0x5d, 0xe8, 0x2c, 0xa4, 0xbf, 0x76, 0x2e, 0xe0, 0xe9, 0x15, 0x26, 0xbe, 0xc1, 0xe6, 0xa8,
	0x52, 0x99, 0x28, 0xd4, 0x35, 0xc7, 0xa8, 0x94, 0x08, 0xd0, 0x6e, 0x1d, 0xb4, 0x75, 0xcd, 0x85,
	0xc8, 0xa6, 0x00, 0x66, 0x76, 0xea, 0x33, 0x2e, 0xf3, 0x86, 0xda, 0xbc, 0xa2, 0x71, 0x2e, 0x61,
	0x58, 0x01, 0xd5, 0x73, 0xb8, 0xa1, 0x38, 0x2a, 0x38, 0x31, 0xff, 0x5a, 0x47, 0x78, 0xb7, 0x61,
	0xc3, 0xfc, 0xeb, 0x56, 0x29, 0x13, 0xde, 0x6d, 0x98, 0x04, 0x86, 0x8e, 0x3e, 0x2f, 0x65, 0xe7,
	0x1b, 0x8c, 0x4e, 0x88, 0x84, 0x77, 0x13, 0x63, 0x42, 0x86, 0xec, 0x29, 0x80, 0x97, 0x03, 0x7c,
	0xc9, 0x36, 0xb9, 0x2b, 0x1a, 0x83, 0xb0, 0x4e, 0xb1, 0x44, 0x58, 0xa7, 0xa8, 0x11, 0x96, 0x61,
	0x84, 0x89, 0x88, 0xd1, 0x20, 0x0c, 0x78, 0x29, 0x3b, 0x7f, 0x2d, 0x18, 0x6b, 0x12, 0xaa, 0x1b,
	0x34, 0x01, 0x8b, 0xa4, 0xe9, 0xbe, 0x3e, 0x1a, 0x8b, 0xa4, 0xb6, 0x79, 0x9e, 0x6d, 0x6d, 0xdb,
	0x3c, 0x8f, 0x3d, 0x87, 0xf6, 0xc2, 0xf3, 0xec, 0xf6, 0x96, 0x51, 0xab, 0xcb, 0x91, 0x77, 0xfe,
	0x33, 0xf2, 0x57, 0xd0, 0xcf, 0x30, 0x8d, 0xd6, 0xd7, 0x24, 0x8b, 0x99, 0x56, 0x7d, 0x7a, 0xc6,
	0x36, 0x97, 0xd5, 0x9d, 0xea, 0xd6, 0x77, 0xea, 0x9e, 0x25, 0xef, 0x3d, 0x6e, 0xc9, 0x9b, 0x2b,
	0xd6, 0x7f, 0xf4, 0x8a, 0xfd, 0x6e, 0xc1, 0xb8, 0x81, 0xc6, 0xde, 0xc1, 0x50, 0x94, 0x43, 0x55,
	0x05, 0xcf, 0xd3, 0xad, 0x1a, 0x6b, 0x73, 0xe7, 0xd5, 0x90, 0xda, 0xeb, 0xb0, 0x1a, 0xaf, 0xe3,
	0x18, 0x7a, 0x3a, 0xd3, 0xb5, 0xa0, 0x82, 0xe9, 0x89, 0x9b, 0x1f, 0x15, 0x77, 0x73, 0x54, 0xdc,
	0xf9, 0xe6, 0xa8, 0xf0, 0xae, 0x76, 0x3d, 0xa1, 0xa3, 0x5f, 0x16, 0xec, 0x1a, 0xae, 0xd9, 0x25,
	0x0c, 0xca, 0x37, 0xc1, 0xb6, 0x88, 0x6b, 0x6c, 0xca, 0xe4, 0xe5, 0x7d, 0x0e, 0xb5, 0xf7, 0xe4,
	0xec, 0xb0, 0x2b, 0xd8, 0xcb, 0xd5, 0x51, 0x9e, 0x75, 0xab, 0xd5, 0xfa, 0x01, 0x7b, 0x58, 0xd2,
	0x39, 0x8c, 0xb4, 0xda, 0x5c, 0xa2, 0x3c, 0xed, 0x8b, 0x66, 0x58, 0xed, 0x4a, 0x3d, 0x28, 0xeb,
	0xe9, 0xeb, 0xaf, 0x87, 0x41, 0x48, 0x37, 0xab, 0x85, 0xeb, 0xc9, 0x78, 0x56, 0x04, 0xcc, 0x02,
	0x79, 0xad, 0xfc, 0xdb, 0x59, 0x98, 0x10, 0x66, 0x89, 0x88, 0x8a, 0xeb, 0xdc, 0x35, 0x9f, 0xe3,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x16, 0xe1, 0x5b, 0xd1, 0x05, 0x00, 0x00,
}
