// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: group.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Group_InsertEmailToGroup_FullMethodName   = "/sendlix.api.v1.Group/InsertEmailToGroup"
	Group_RemoveEmailFromGroup_FullMethodName = "/sendlix.api.v1.Group/RemoveEmailFromGroup"
	Group_CheckEmailInGroup_FullMethodName    = "/sendlix.api.v1.Group/CheckEmailInGroup"
)

// GroupClient is the client API for Group service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupClient interface {
	InsertEmailToGroup(ctx context.Context, in *InsertEmailToGroupRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	RemoveEmailFromGroup(ctx context.Context, in *RemoveEmailFromGroupRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	CheckEmailInGroup(ctx context.Context, in *CheckEmailInGroupRequest, opts ...grpc.CallOption) (*CheckEmailInGroupResponse, error)
}

type groupClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupClient(cc grpc.ClientConnInterface) GroupClient {
	return &groupClient{cc}
}

func (c *groupClient) InsertEmailToGroup(ctx context.Context, in *InsertEmailToGroupRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, Group_InsertEmailToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) RemoveEmailFromGroup(ctx context.Context, in *RemoveEmailFromGroupRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, Group_RemoveEmailFromGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) CheckEmailInGroup(ctx context.Context, in *CheckEmailInGroupRequest, opts ...grpc.CallOption) (*CheckEmailInGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEmailInGroupResponse)
	err := c.cc.Invoke(ctx, Group_CheckEmailInGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServer is the server API for Group service.
// All implementations must embed UnimplementedGroupServer
// for forward compatibility.
type GroupServer interface {
	InsertEmailToGroup(context.Context, *InsertEmailToGroupRequest) (*UpdateResponse, error)
	RemoveEmailFromGroup(context.Context, *RemoveEmailFromGroupRequest) (*UpdateResponse, error)
	CheckEmailInGroup(context.Context, *CheckEmailInGroupRequest) (*CheckEmailInGroupResponse, error)
	mustEmbedUnimplementedGroupServer()
}

// UnimplementedGroupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupServer struct{}

func (UnimplementedGroupServer) InsertEmailToGroup(context.Context, *InsertEmailToGroupRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertEmailToGroup not implemented")
}
func (UnimplementedGroupServer) RemoveEmailFromGroup(context.Context, *RemoveEmailFromGroupRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEmailFromGroup not implemented")
}
func (UnimplementedGroupServer) CheckEmailInGroup(context.Context, *CheckEmailInGroupRequest) (*CheckEmailInGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEmailInGroup not implemented")
}
func (UnimplementedGroupServer) mustEmbedUnimplementedGroupServer() {}
func (UnimplementedGroupServer) testEmbeddedByValue()               {}

// UnsafeGroupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupServer will
// result in compilation errors.
type UnsafeGroupServer interface {
	mustEmbedUnimplementedGroupServer()
}

func RegisterGroupServer(s grpc.ServiceRegistrar, srv GroupServer) {
	// If the following call pancis, it indicates UnimplementedGroupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Group_ServiceDesc, srv)
}

func _Group_InsertEmailToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertEmailToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).InsertEmailToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_InsertEmailToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).InsertEmailToGroup(ctx, req.(*InsertEmailToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_RemoveEmailFromGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEmailFromGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).RemoveEmailFromGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_RemoveEmailFromGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).RemoveEmailFromGroup(ctx, req.(*RemoveEmailFromGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_CheckEmailInGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEmailInGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).CheckEmailInGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_CheckEmailInGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).CheckEmailInGroup(ctx, req.(*CheckEmailInGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Group_ServiceDesc is the grpc.ServiceDesc for Group service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Group_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sendlix.api.v1.Group",
	HandlerType: (*GroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertEmailToGroup",
			Handler:    _Group_InsertEmailToGroup_Handler,
		},
		{
			MethodName: "RemoveEmailFromGroup",
			Handler:    _Group_RemoveEmailFromGroup_Handler,
		},
		{
			MethodName: "CheckEmailInGroup",
			Handler:    _Group_CheckEmailInGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "group.proto",
}
