// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InsertEmailToGroupRequest struct {
	Emails               []*EmailData      `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	GroupId              string            `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Substitutions        map[string]string `protobuf:"bytes,3,rep,name=substitutions,proto3" json:"substitutions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InsertEmailToGroupRequest) Reset()         { *m = InsertEmailToGroupRequest{} }
func (m *InsertEmailToGroupRequest) String() string { return proto.CompactTextString(m) }
func (*InsertEmailToGroupRequest) ProtoMessage()    {}
func (*InsertEmailToGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0}
}

func (m *InsertEmailToGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertEmailToGroupRequest.Unmarshal(m, b)
}
func (m *InsertEmailToGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertEmailToGroupRequest.Marshal(b, m, deterministic)
}
func (m *InsertEmailToGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertEmailToGroupRequest.Merge(m, src)
}
func (m *InsertEmailToGroupRequest) XXX_Size() int {
	return xxx_messageInfo_InsertEmailToGroupRequest.Size(m)
}
func (m *InsertEmailToGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertEmailToGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertEmailToGroupRequest proto.InternalMessageInfo

func (m *InsertEmailToGroupRequest) GetEmails() []*EmailData {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *InsertEmailToGroupRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *InsertEmailToGroupRequest) GetSubstitutions() map[string]string {
	if m != nil {
		return m.Substitutions
	}
	return nil
}

type RemoveEmailFromGroupRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEmailFromGroupRequest) Reset()         { *m = RemoveEmailFromGroupRequest{} }
func (m *RemoveEmailFromGroupRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveEmailFromGroupRequest) ProtoMessage()    {}
func (*RemoveEmailFromGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{1}
}

func (m *RemoveEmailFromGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEmailFromGroupRequest.Unmarshal(m, b)
}
func (m *RemoveEmailFromGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEmailFromGroupRequest.Marshal(b, m, deterministic)
}
func (m *RemoveEmailFromGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEmailFromGroupRequest.Merge(m, src)
}
func (m *RemoveEmailFromGroupRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveEmailFromGroupRequest.Size(m)
}
func (m *RemoveEmailFromGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEmailFromGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEmailFromGroupRequest proto.InternalMessageInfo

func (m *RemoveEmailFromGroupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RemoveEmailFromGroupRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type UpdateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AffectedRows         int64    `protobuf:"varint,3,opt,name=affectedRows,proto3" json:"affectedRows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{2}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateResponse) GetAffectedRows() int64 {
	if m != nil {
		return m.AffectedRows
	}
	return 0
}

type CheckEmailInGroupRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckEmailInGroupRequest) Reset()         { *m = CheckEmailInGroupRequest{} }
func (m *CheckEmailInGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CheckEmailInGroupRequest) ProtoMessage()    {}
func (*CheckEmailInGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{3}
}

func (m *CheckEmailInGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckEmailInGroupRequest.Unmarshal(m, b)
}
func (m *CheckEmailInGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckEmailInGroupRequest.Marshal(b, m, deterministic)
}
func (m *CheckEmailInGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckEmailInGroupRequest.Merge(m, src)
}
func (m *CheckEmailInGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CheckEmailInGroupRequest.Size(m)
}
func (m *CheckEmailInGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckEmailInGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckEmailInGroupRequest proto.InternalMessageInfo

func (m *CheckEmailInGroupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CheckEmailInGroupRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type CheckEmailInGroupResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckEmailInGroupResponse) Reset()         { *m = CheckEmailInGroupResponse{} }
func (m *CheckEmailInGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CheckEmailInGroupResponse) ProtoMessage()    {}
func (*CheckEmailInGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{4}
}

func (m *CheckEmailInGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckEmailInGroupResponse.Unmarshal(m, b)
}
func (m *CheckEmailInGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckEmailInGroupResponse.Marshal(b, m, deterministic)
}
func (m *CheckEmailInGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckEmailInGroupResponse.Merge(m, src)
}
func (m *CheckEmailInGroupResponse) XXX_Size() int {
	return xxx_messageInfo_CheckEmailInGroupResponse.Size(m)
}
func (m *CheckEmailInGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckEmailInGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckEmailInGroupResponse proto.InternalMessageInfo

func (m *CheckEmailInGroupResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func init() {
	proto.RegisterType((*InsertEmailToGroupRequest)(nil), "sendlix.api.v1.InsertEmailToGroupRequest")
	proto.RegisterMapType((map[string]string)(nil), "sendlix.api.v1.InsertEmailToGroupRequest.SubstitutionsEntry")
	proto.RegisterType((*RemoveEmailFromGroupRequest)(nil), "sendlix.api.v1.RemoveEmailFromGroupRequest")
	proto.RegisterType((*UpdateResponse)(nil), "sendlix.api.v1.UpdateResponse")
	proto.RegisterType((*CheckEmailInGroupRequest)(nil), "sendlix.api.v1.CheckEmailInGroupRequest")
	proto.RegisterType((*CheckEmailInGroupResponse)(nil), "sendlix.api.v1.CheckEmailInGroupResponse")
}

func init() { proto.RegisterFile("group.proto", fileDescriptor_e10f4c9b19ad8eee) }

var fileDescriptor_e10f4c9b19ad8eee = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x89, 0x12, 0x60, 0x0a, 0x05, 0x56, 0x11, 0x72, 0x83, 0x84, 0x2a, 0x9f, 0x5c, 0x90,
	0xd6, 0xa2, 0xbd, 0x20, 0xc4, 0x01, 0x01, 0x05, 0x05, 0x89, 0xcb, 0x02, 0x17, 0x2e, 0x68, 0x6d,
	0x4f, 0x9d, 0x25, 0xf6, 0xae, 0xf1, 0xac, 0x43, 0xfb, 0xe3, 0xf8, 0x6d, 0x20, 0x6f, 0x6c, 0x84,
	0xf3, 0x81, 0x22, 0xf5, 0x94, 0xbc, 0x9d, 0xf7, 0x66, 0xde, 0xbc, 0x91, 0xe1, 0x20, 0xab, 0x4c,
	0x5d, 0xf2, 0xb2, 0x32, 0xd6, 0xb0, 0x43, 0x42, 0x9d, 0xe6, 0xea, 0x92, 0xcb, 0x52, 0xf1, 0xe5,
	0xb3, 0xe9, 0xbd, 0xf3, 0x42, 0xaa, 0xfc, 0xad, 0xb4, 0x72, 0x45, 0x08, 0x7e, 0x7b, 0x70, 0x34,
	0xd3, 0x84, 0x95, 0x75, 0x95, 0xcf, 0xe6, 0x7d, 0xa3, 0x16, 0xf8, 0xa3, 0x46, 0xb2, 0x2c, 0x80,
	0x31, 0x36, 0xcf, 0xe4, 0x7b, 0xc7, 0xc3, 0xf0, 0xe0, 0x14, 0xf8, 0x5f, 0xbd, 0x68, 0x2b, 0xcc,
	0x87, 0x9b, 0x6e, 0xe2, 0x2c, 0xf5, 0x07, 0xc7, 0x5e, 0x78, 0x5b, 0x74, 0x90, 0xc5, 0x70, 0x97,
	0xea, 0x98, 0xac, 0xb2, 0xb5, 0x55, 0x46, 0x93, 0x3f, 0x74, 0x4d, 0x5e, 0xf2, 0xbe, 0x29, 0xbe,
	0x73, 0x3e, 0xff, 0xf4, 0xaf, 0xfc, 0x5c, 0xdb, 0xea, 0x4a, 0xf4, 0x5b, 0x4e, 0x5f, 0x01, 0xdb,
	0x24, 0xb1, 0xfb, 0x30, 0x5c, 0xe0, 0x95, 0xef, 0x39, 0x3f, 0xcd, 0x5f, 0x36, 0x81, 0xd1, 0x52,
	0xe6, 0x35, 0xb6, 0x1e, 0x57, 0xe0, 0xc5, 0xe0, 0xb9, 0x17, 0x7c, 0x84, 0x47, 0x02, 0x0b, 0xb3,
	0x44, 0x67, 0xe0, 0x5d, 0x65, 0x8a, 0x5e, 0x04, 0x13, 0x18, 0xb9, 0x45, 0xdb, 0x66, 0x2b, 0xb0,
	0x7b, 0xe9, 0x60, 0x0e, 0x87, 0x5f, 0xca, 0x54, 0x5a, 0x14, 0x48, 0xa5, 0xd1, 0x84, 0x0d, 0x97,
	0xea, 0x24, 0x41, 0x22, 0xd7, 0xe3, 0x96, 0xe8, 0x60, 0x53, 0x29, 0x90, 0x48, 0x66, 0x9d, 0xad,
	0x0e, 0xb2, 0x00, 0xee, 0xc8, 0x8b, 0x0b, 0x4c, 0x2c, 0xa6, 0xc2, 0xfc, 0x6c, 0x92, 0xf3, 0xc2,
	0xa1, 0xe8, 0xbd, 0x05, 0x1f, 0xc0, 0x7f, 0x33, 0xc7, 0x64, 0xe1, 0x7c, 0xcf, 0xf4, 0xb5, 0x5c,
	0x9f, 0xc1, 0xd1, 0x96, 0x5e, 0xed, 0x02, 0x0f, 0x61, 0x8c, 0x97, 0x8a, 0x6c, 0xe7, 0xbf, 0x45,
	0xa7, 0xbf, 0x06, 0x30, 0x72, 0x4c, 0x26, 0x81, 0x6d, 0x1e, 0x91, 0x9d, 0xec, 0x7d, 0xe8, 0xe9,
	0xe3, 0x75, 0x6a, 0x3f, 0xc3, 0xe0, 0x06, 0x43, 0x98, 0x6c, 0x3b, 0x13, 0x7b, 0xba, 0xae, 0xfc,
	0xcf, 0x31, 0xf7, 0x18, 0xf3, 0x1d, 0x1e, 0x6c, 0x04, 0xc1, 0xc2, 0x75, 0xd9, 0xae, 0xdc, 0xa7,
	0x27, 0x7b, 0x30, 0xbb, 0x59, 0xaf, 0x9f, 0x7c, 0x0d, 0x33, 0x65, 0xe7, 0x75, 0xcc, 0x13, 0x53,
	0x44, 0xad, 0x30, 0xca, 0xcc, 0x37, 0x4a, 0x17, 0x91, 0xd2, 0x16, 0x2b, 0x2d, 0xf3, 0xc8, 0x7d,
	0xa7, 0xf1, 0xd8, 0xfd, 0x9c, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xa7, 0x58, 0xd8, 0xde,
	0x03, 0x00, 0x00,
}
